apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-flask
  template:
    metadata:
      labels:
        app: api-flask
    spec:
      containers:
      - name: api-flask
        image: api-flask:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
